### ISSUE TITLE
Documentation still says ASF 2.0 license instead of new-BSD

### ISSUE THREAD

**Issue by jameswennmacher** [FasterXML/StaxMate#8]
Hi @cowtowncoder.  I noticed that the comments about updating the documentation in https://github.com/FasterXML/StaxMate/issues/7 did not occur.  The following items at least still reference ASF 2.0 instead of new-BSD license:
- README.md
- wiki at https://github.com/FasterXML/StaxMate/wiki

**Comment by cowtowncoder** [comment]
Thanks. Those did fall through the cracks. I will go ahead and update.

**Comment by cowtowncoder** [comment]
Fixed.
